events {}
#le dicen al contenedor que respete los tipos de mimes 
#respeta los mimes de los archivos 
#si no se incluyen todos los archivos los pasa a texto plano 
http {
    include       /etc/nginx/mime.types;
    default_type application/octet-stream;
    #entra al http y redireciona a https 
    server {
        listen 80;#porque asi se definio en el dockerfile
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;##el puerto de por defecto de nginx asignado o utilizado por buenas practicas
        server_name localhost;
        
        ssl_certificate     /etc/letsencrypt/live/localhost/fullchain.pem;#son para acceder los archivos 
        ssl_certificate_key /etc/letsencrypt/live/localhost/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;#nivel de cifrado alto y 

        root /usr/share/nginx/html;
        index index.html;
        location /{
            try_files $uri /index.html;
        }
    }
}